[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Playwright padrões
addopts =
    --browser chromium
    -v
    --tb=short

# Ignorar warnings desnecessários
filterwarnings =
    ignore::DeprecationWarning
